name: Build (MacOS)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check_examples:
    name: Check Examples
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - uses: Swatinem/rust-cache@v1

      - name: Run all examples
        run: |
          cd builder-pattern
          for example in examples/*.rs
          do
            e=${example##*/}
            cargo run --example ${e%.*}
          done

      - name: Run no-future examples
        run: |
          cd test-no-future
          for example in examples/*.rs
          do
            e=${example##*/}
            cargo run --example ${e%.*}
            result=$?
            if [[ $e == fail-* ]]; then
              if [[ $result -eq 0 ]]; then
                echo "Error: example '$e' should fail!"
                exit 1
            elif [[ $result -ne 0 ]]; then
              exit 1
            fi
          done;
