name: Build (Ubuntu)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  # Only lints for Ubuntu.
  lint:
    name: Format & Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1

      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run clippy
        if: always()
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings

  check_examples:
    name: Check Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - uses: Swatinem/rust-cache@v1

      - name: Run all examples
        run: |
          cd builder-pattern
          for example in examples/*.rs
          do
            e=${example##*/}
            cargo run --example ${e%.*}
          done

      - name: Run no-future examples
        run: |
          cd test-no-future
          for example in examples/*.rs
          do
            e=${example##*/}
            cargo run --example ${e%.*}
            result=$?
            if [[ $e == fail-* ]]; then
              if [[ $result -eq 0 ]]; then
                echo "Error: example '$e' should fail!"
                exit 1
              fi
            elif [[ $result -ne 0 ]]; then
              exit 1
            fi
          done

  # Only test docs for Ubuntu.
  doc_tests:
    name: Documentation Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - uses: Swatinem/rust-cache@v1

      - name: Run doctest
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc
