name: Build (Windows)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check_examples:
    name: Check Examples
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - uses: Swatinem/rust-cache@v1

      - name: Run all examples
        run: |
          .\scripts\test-examples.ps1 builder-pattern

      - name: Run no-future examples
        run: |
          .\scripts\test-examples.ps1 test-no-future
