name: Build (Windows)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check_examples:
    name: Check Examples
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - uses: Swatinem/rust-cache@v1

      - name: Run all examples
        run: |
          cd builder-pattern
          Get-ChildItem examples -Filter *.rs |
          Foreach-Object {
            cargo run --example $_.BaseName
            if ($LASTEXITCODE -ne 0) {
              $Host.SetShouldExit($LASTEXITCODE)
              exit
            }
          }

      - name: Run no-future examples
        run: |
          ./scripts/test-no-future.ps1
