name: Build (Ubuntu)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  # Only lints for Ubuntu.
  lint:
    name: Format & Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        if: always()
        run: cargo clippy -- -D warnings

  check_examples:
    name: Check Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
      - uses: Swatinem/rust-cache@v2

      - name: Run all examples
        run: |
          ./scripts/test-examples.sh builder-pattern

      - name: Run no-future examples
        run: |
          ./scripts/test-examples.sh test-no-future

  # Only test docs for Ubuntu.
  doc_tests:
    name: Documentation Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
      - uses: Swatinem/rust-cache@v2

      - name: Run doctest
        run: cargo test --doc
